### ISSUE TITLE
MacOs build

### ISSUE THREAD

**Issue by Octopus773** [AnonymusRaccoon/Bomberman#50]
It could nice for the CI to build on MacOs

**Comment by AnonymusRaccoon** [comment]
It is not fixed yet, the project still does not compile on macos.

**Comment by Arthi-chaud** [comment]
I spend some time trying to make the project compile on the OS (Github Action & my personal machine)

To me, the reason why it doesn't compile has something to do with cross-platform-compatible code. I've tried using multiple compilers (their most recent release): GCC, CLang, as well as using generation methods: Makefiles or Ninja. And everytime, it 
says here:
https://github.com/AnonymusRaccoon/Bomberman/blob/ad7b10e6878088662673abedbae54b0ee657ff4c/sources/Models/Vector3.hpp#L171
that a semi colon is missing between 'const' and 'requires'. Note that the use of 'requires' here is recent (C++ 20)

I don't think it's wise to keep trying, at least this week, since it's not part of the mandatory section.
